// Defines the InventoryItem entity for Room database
package com.lionico.core.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.LocalDate

/**
 * Represents an inventory item in the database.
 * @property id Unique identifier for the item (auto-generated by Room).
 * @property itemName Name of the item (e.g., "Fertilizer", "Seeds").
 * @property quantity Current stock quantity of the item.
 * @property lastUpdated Date when the item was last updated.
 */
@Entity(tableName = "inventory_items")
data class InventoryItem(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val itemName: String,
    var quantity: Int,
    val lastUpdated: LocalDate = LocalDate.now()
)
