// Defines the ManualEntry entity with soil-specific fields
package com.lionico.core.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.LocalDate

/**
 * Represents a manual entry in the database.
 * @property id Unique identifier for the entry (auto-generated by Room).
 * @property tabType Type of entry (e.g., "soil", "weather").
 * @property entryDate Date when the entry was created.
 * @property field1 Soil pH (for soil entries).
 * @property field2 Soil moisture (for soil entries).
 * @property field3 Soil nutrient level (for soil entries).
 * @property notes Additional notes for the entry.
 */
@Entity(tableName = "manual_entries")
data class ManualEntry(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val tabType: String,
    val entryDate: LocalDate = LocalDate.now(),
    val field1: String = "", // pH
    val field2: String = "", // Moisture
    val field3: String = "", // Nutrients (N, P, K)
    val notes: String = ""
)
